name: Dummy Workflow
on:
  pull_request:
    branches: [OrgSource]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Hello
        run: echo "This is a dummy workflow"
